### ISSUE TITLE
Bug at add new user

### ISSUE THREAD

**Issue by Dungnn197** [sonnv10121997/ise#39]
Enter all required field but can't create user[
![Capture](https://user-images.githubusercontent.com/41223254/55125364-10028900-513c-11e9-9c28-d549092c9a99.PNG)
](url)

**Comment by sonnv10121997** [comment]
`ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_slug"`
